# Generated by Django 6.0.4 on 2026-04-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgame',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('playing', 'Playing'), ('completed', 'Completed')], default='saved', max_length=20),
        ),
    ]
