GENRE_TAG_OPTIONS = [
    "Action",
    "Adventure",
    "Arcade",
    "Board",
    "Card",
    "Casual",
    "Educational",
    "Family",
    "Fighting",
    "Indie",
    "Massively Multiplayer",
    "Platformer",
    "Puzzle",
    "Racing",
    "RPG",
    "Shooter",
    "Simulation",
    "Sports",
    "Strategy",
]

PLATFORM_TAG_OPTIONS = [
    "PC",
    "macOS",
    "Linux",
    "PlayStation 5",
    "PlayStation 4",
    "Xbox Series X/S",
    "Xbox One",
    "Nintendo Switch",
    "iOS",
    "Android",
]