# Generated by Django 6.0.4 on 2026-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personality_tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
