# Generated by Django 6.0.4 on 2026-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profile_personality_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='excluded_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='platform_tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
