# Generated by Django 6.0.4 on 2026-04-19 18:20

import profile_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profile_excluded_tags_profile_genre_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genre_tags',
            field=models.JSONField(blank=True, null=True, validators=[profile_app.validators.validate_genre_tags]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform_tags',
            field=models.JSONField(blank=True, null=True, validators=[profile_app.validators.validate_platform_tags]),
        ),
    ]
